language: php
php:
  - '7.1'
install:
  - rm -rf /tmp/craft3
  - composer create-project craftcms/craft /tmp/craft3
  - php bin/setup/travis.php
  - cd /tmp/craft3 && composer require markhuot/craftql dev-master
  - cd /tmp/craft3 && composer require phpunit/phpunit
script:
  - cd /tmp/craft3 && vendor/bin/phpunit vendor/markhuot/craftql/tests/ --testdox