language: php
php:
  - '7.1'
install:
  - rm -rf /home/travis/build/craftcms/craft
  - composer create-project craftcms/craft /home/travis/build/craftcms/craft
  - php bin/setup/travis.php
  - cd /home/travis/build/craftcms/craft
  - composer require markhuot/craftql dev-master
  - composer require phpunit/phpunit
script:
  - vendor/bin/phpunit vendor/markhuot/craftql/tests/ --testdox