language: php
php:
  - '7.1'
services:
  - mysql
env:
  - DB_USER="root" DB_PASSWORD="" DB_DATABASE="craftql"
cache:
  directories:
    - /home/travis/build/vendor_cache
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS craftql;'
  - composer create-project --no-install craftcms/craft /home/travis/build/craftcms/craft
  - printf '\nDB_DATABASE="craftql"' >> /home/travis/build/craftcms/craft/.env
  - cat /home/travis/build/craftcms/craft/.env
  - mv /home/travis/build/vendor_cache /home/travis/build/craftcms/craft/vendor 2>/dev/null
install:
  - cd /home/travis/build/craftcms/craft
  - composer config repositories.craftql path /home/travis/build/markhuot/craftql
  - composer config minimum-stability dev
  - composer require markhuot/craftql:dev-master phpunit/phpunit
  - ./craft install --email=foo@example.com --username=admin --password=foobar --siteName="Test Site" --siteUrl="http://localhost" --language=en
  - php vendor/markhuot/craftql/bin/setup/install.php
  - chmod +x craft
  - ./craft craftql/tools/seed
script:
  - vendor/bin/phpunit --bootstrap vendor/markhuot/craftql/bootstrap.php vendor/markhuot/craftql/tests/
before_cache:
  - mv /home/travis/build/craftcms/craft/vendor /home/travis/build/vendor_cache
  - rm -rf /home/travis/build/vendor_cache/markhuot
