language: php
php:
  - '7.1'
services:
  - mysql
env:
  - DB_USER="root" DB_PASSWORD="" DB_DATABASE="craftql"
cache:
  directories:
    - /home/travis/build/craftcms/craft/vendor
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS craftql;'
  - composer create-project --no-install craftcms/craft /home/travis/build/craftcms/craft
  - php bin/setup/travis.php
install:
  - cd /home/travis/build/craftcms/craft
  - composer require markhuot/craftql @dev
  - composer require phpunit/phpunit
  - mysql -u root --password="" craftql < /home/travis/build/markhuot/craftql/sql/bootstrap.sql
  - php vendor/markhuot/craftql/bin/setup/install.php
  - chmod +x craft
  - ./craft craftql/tools/seed
script:
  - vendor/bin/phpunit --bootstrap vendor/markhuot/craftql/bootstrap.php vendor/markhuot/craftql/tests/ --testdox